### PR TITLE
Reorg

### PR DESCRIPTION
**Pull request by JordanCheney**
I'm not sure what the review process should be for this merge. A few notes-

Transforms without documentation
==========================
core/downsampletraining.cpp
core/discardtemplates.cpp
core/distributetemplate.cpp
core/event.cpp
core/progresscounter.cpp
distance/zscore.cpp
gallery/video.cpp
gallery/vbb.cpp
gallery/binary.cpp
imgproc/multiscale.cpp
imgproc/transpose.cpp
io/output.cpp
io/galleryoutput.cpp
metadata/fileexclusion.cpp

Files with more than one transform (these aren't bugs but are also not ideal)
=========================================================
classification/svm.cpp
classification/lda.cpp
classification/forest.cpp
core/stream.cpp
format/video.cpp
format/mtx.cpp
gallery/video.cpp
gallery/binary.cpp
gui/show.cpp
imgproc/gabor.cpp
imgproc/multiscale.cpp
imgproc/slidingwindow.cpp
imgproc/productquantization.cpp

### CODE REVIEW

**Comment by jklontz** [comment]
This is great and should be merged ASAP

**Comment by sklum** [comment]
Bravo sir.

**Comment by JordanCheney** [comment]
Ok going for my first command line merge. Bear with me

**Comment by bklare** [comment]
This is great. Thank you @JordanCheney

**Pull request merged**
