### PR TITLE
Plotting customization

### PR DESCRIPTION
**Pull request by bhklein**
This PR addresses some of the issues raised in #390.

* Added separate plot options for DET, and IET
* Set default ticks to 10% increments.
* Allow setting of x-axis limits
* Specify log/linear axis
* Added option to plot first two metadata pages
* Added option to output metadata tables to csv files
* Updated plotting docs

### CODE REVIEW

**Comment by bklare** [comment]
Just ran the csv portion of this code. Perfect. Thank you @bhklein !

**Comment by bhklein** [comment]
glad to hear @bklare

**Comment by jklontz** [comment]
@caotto can you review?

**Comment by caotto** [comment]
What is the current status of windows support for the project? I think there was some talk about dropping support for VS2012, has that happened already?

**Comment by caotto** [comment]
@jklontz ping

**Comment by caotto** [comment]
Anyway the build being broken on windows/vs2012 is more or less unrelated to this PR I guess. 

Regardless of future plans, uniform handling of plot options is a good improvement.

Some examples of setting various options in the documentation would be a good idea, e.g. I don't know what the syntax for setting breaks/ticks is, users in general may not know offhand how a QPointF is expected to be specified.

**Comment by jklontz** [comment]
@caotto I'd like to move to MSVC2013, but as you're the only windows developer at this point, you're welcome to make the call.

**Comment by caotto** [comment]
Well to speak to my immediate concern, does that mean the project will build if I do install VS2013, or just that no one is trying to maintain windows compatibility

**Comment by jklontz** [comment]
I think that currently no one tracks the build status on windows, so we don't know when we break windows compatibility.

**Comment by bhklein** [comment]
docs updated

**Comment by caotto** [comment]
:+1:

**Comment by bhklein** [comment]
thanks

**Pull request merged**
